site_name: Milime Wiki
site_url: https://milime.wiki/
docs_dir: wiki
repo_url: https://github.com/Jumpticket-Games/Milime-Wiki
repo_name: Milime-Wiki

theme:
  name: material
  custom_dir: replace
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: RTX ON!!!
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: RTX OFF!!!
  icon:
    repo: fontawesome/brands/github
  font:
    text: Noto Serif SC
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - navigation.tracking

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      name: Mail
      link: mailto:contact@jumpticket.games
    - icon: material/home
      name: Jumpticket Games
      link: https://jumpticket.games/

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - meta
