site_name: Milime Wiki
docs_dir: wiki
repo_url: https://github.com/Jumpticket-Games/Milime-Wiki
repo_name: Milime-Wiki
theme:
  name: material
  language: zh
  palette:
    # - primary: white
    # - accent: teal
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Cairo
    code: JetBrains Mono
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.integrate
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@jumpticket.games
plugins:
  - search
